### ISSUE TITLE
OK... 

### ISSUE THREAD

**Issue by kdschlosser** [wolph/speedups#1]
alright, first thing to start off at.

This is way over complicated for what you are attempting to do.

You are going to laugh at how simple it is once I tell you.
Get rid of the h file and the pxd file. they are not needed.

write the code in 100% python and compile that  py file with Cython. That's it you are done.  You can convert just about any python module to c code using Cython and then compile it into an extension module. You do not need to write specific header files and Cython source files unless you are accessing  c libraries which it does not appear that you are. 

Setup script

```python
import os
import sys
from setuptools import setup, Extension

try:
    from Cython.Build import cythonize
    have_cython = True
except ImportError:
    have_cython = False



PACKAGE = 'speedups'
PACKAGEDIR = 'speedups'
BUILD_OPTIONS = {'build_base': 'build'}


if have_cython:
    def build_extensions(p, mod_name):
        modules = []
        for f_name in os.listdir(p):
            path = os.path.join(p, f_name)

            if os.path.isdir(path):
                mod_name += '.' + f_name
                modules.extend(build_extensions(path, mod_name))
            elif path.endswith('.py') and '__init__.py' not in path:
                mod = os.path.splitext(f_name)[0]
                mod = Extension(
                    name=mod_name + '.' + mod,
                    sources=[path],
                    include_dirs=[p],
                )

                modules.append(mod)

        return modules

    module_list = build_extensions(PACKAGEDIR, PACKAGE)

    mods = cythonize(
        module_list,
        # nthreads=os.cpu_count(),
        compiler_directives={
            'embedsignature': True,
            'language_level': 2,
        }
    )

    setup(
        name='some package',
        version='0.0.1',
        description='some description',
        long_description='some long description',
        author='some author',
        author_email='some email',
        url='some url',
        download_url='some download url',
        license='some license',
        ext_modules=mods,
        options={'build': BUILD_OPTIONS},
    )

```

run the setup using the following command
```
python setup.py build_ext --inplace
```

I really do not see any code that has to be written in Cython or in C. Tere is no reason why you should not be able to do this using pure python and doing a C conversion using Cython.

as a suggestion. use the pyproject.toml file to set up the pip build environment.

```toml
[build-system]
requires=[
    "setuptools>=57.5.0",
    "wheel",
    "pyMSVC;sys_platform=='win32'",
    "cython==0.29.24"
]
build-backend="setuptools.build_meta"
```

and here is the setup file to use with the pyproject.toml file.

```python
import os
import sys
from setuptools import setup, Extension

try:
    from Cython.Build import cythonize
    have_cython = True
except ImportError:
    have_cython = False

if 'build_ext' not in sys.argv:
    sys.argv.insert(1, --inplace')
    sys.argv.insert(1, 'build_ext')

# fixes MSVC compiler detection in Setup tools so it will compile properly on Windows. 
if sys.platform.startswith('win'):
    import pyMSVC
    environment = pyMSVC.setup_environment()
    print(environment)


PACKAGE = 'speedups'
PACKAGEDIR = 'speedups'
BUILD_OPTIONS = {'build_base': 'build'}


if have_cython:
    def build_extensions(p, mod_name):
        modules = []
        for f_name in os.listdir(p):
            path = os.path.join(p, f_name)

            if os.path.isdir(path):
                mod_name += '.' + f_name
                modules.extend(build_extensions(path, mod_name))
            elif path.endswith('.py') and '__init__.py' not in path:
                mod = os.path.splitext(f_name)[0]
                mod = Extension(
                    name=mod_name + '.' + mod,
                    sources=[path],
                    include_dirs=[p],
                )

                modules.append(mod)

        return modules

    module_list = build_extensions(PACKAGEDIR, PACKAGE)

    mods = cythonize(
        module_list,
        # nthreads=os.cpu_count(),
        compiler_directives={
            'embedsignature': True,
            'language_level': 2,
        }
    )

    setup(
        name='some package',
        version='0.0.1',
        description='some description',
        long_description='some long description',
        author='some author',
        author_email='some email',
        url='some url',
        download_url='some download url',
        license='some license',
        ext_modules=mods,
        options={'build': BUILD_OPTIONS},
    )

```

**Comment by wolph** [comment]
> You are going to laugh at how simple it is once I tell you. Get rid of the h file and the pxd file. they are not needed.
> 
> write the code in 100% python and compile that py file with Cython. That's it you are done. You can convert just about any python module to c code using Cython and then compile it into an extension module. You do not need to write specific header files and Cython source files unless you are accessing c libraries which it does not appear that you are.

The header file contains some actual code here so it is very much needed :)
Those functions are not universally available on all platforms.

> I really do not see any code that has to be written in Cython or in C. Tere is no reason why you should not be able to do this using pure python and doing a C conversion using Cython.

There are a few nuances here that require cython:

https://github.com/wolph/speedups/blob/fd6d8a03b3082ad26f09c59d43533940361c328c/speedups/psycopg_array.pyx#L57-L58
https://github.com/wolph/speedups/blob/fd6d8a03b3082ad26f09c59d43533940361c328c/speedups/psycopg_array.pyx#L67

Also, I'm linking directly into the numpy internals :)

> as a suggestion. use the pyproject.toml file to set up the pip build environment.
> 
> ```toml
> [build-system]
> requires=[
>     "setuptools>=57.5.0",
>     "wheel",
>     "pyMSVC;sys_platform=='win32'",
>     "cython==0.29.24"
> ]
> build-backend="setuptools.build_meta"
> ```

Besides the `pyMSVC` requirement, isn't that exactly the same as what I'm doing right now?
I currently have no direct need for Windows support as I'm not using WIndows, but that could be useful. My ultimate plan for this library is to move the C/cython speedup code from my other repositories to this library so all other libraries are very quick and easy to build with no complicated requirements.

Ideally there would be a good way to keep packages with Cython extensions PEP 517 compliant, but a custom `setup.py` seems to be a requirement currently :(

This modification is certainly useful for me. For the PostgreSQL/psycopg part I don't care much for the speedups on Windows, but if I want to move the speedups from `numpy-stl` I will definitely want to have the speedups working for Windows as well.

**Comment by kdschlosser** [comment]
well here is an example of what the hton.h file would look like in python. This is pseudo code and I have not tested it, it is for example essentially.

```python
import ctypes
import sys
import platform


def _get_libc():
    for lib in ('glibc.so', 'libc.so'):
        try:
            return ctypes.CDLL(lib)
        except:  # NOQA
            pass
    
    raise RuntimeError('unable to locate libc')
    
    
if platform.system() == 'Windows':
    _libc = ctypes.windll.msvcrt
    _ucrt_base = ctypes.windll.ucrtbase_clr0400

    _memcpy = _libc.memcpy
    
    _byteswap_ushort = _ucrt_base._byteswap_ushort
    _byteswap_ushort.restype = ctypes.c_ushort
    
    _byteswap_ulong = _ucrt_base._byteswap_ulong
    _byteswap_ulong.restype = ctypes.c_ulong
    
    _byteswap_uint64 = _ucrt_base._byteswap_uint64
    _byteswap_uint64.restype = ctypes.c_uint64
    
    def apg_bswap16(x):
        x = ctypes.c_ushort(x)
        return _byteswap_ushort(x)
    
    
    def apg_bswap32(x):
        x = ctypes.c_ulong(x)
        return _byteswap_ulong(x)
    
    
    def apg_bswap64(x):
        x = ctypes.c_uint64(x)
        return _byteswap_uint64(x)
    

# __sun__ 
elif platform.system() == 'SunOS':
    _libc = _get_libc()

    _memcpy = _libc.memcpy
    
    _BSWAP_16 = _libc.BSWAP_16
    _BSWAP_16.restype = ctypes.c_uint16
    
    _BSWAP_32 = _libc.BSWAP_32
    _BSWAP_32.restype = ctypes.c_uint32
    
    _BSWAP_64 = _libc.BSWAP_64
    _BSWAP_64.restype = ctypes.c_uint64

    def apg_bswap16(x):
        x = ctypes.c_uint16(x)
        return _BSWAP_16(x)
    
    
    def apg_bswap32(x):
        x = ctypes.c_uint32(x)
        return _BSWAP_32(x)
    
    
    def apg_bswap64(x):
        x = ctypes.c_uint64(x)
        return _BSWAP_64(x)

# __APPLE__
elif platform.system() == 'Darwin':
    _libc = ctypes.CDLL("libc.dylib", ctypes.RTLD_GLOBAL)
    _libkern = ctypes.CDLL('libkern.dylib', ctypes.RTLD_GLOBAL)

    _memcpy = _libc.memcpy
    
    _OSSwapInt16 = _libkern.OSSwapInt16
    _OSSwapInt16.restype = ctypes.c_uint16
    
    _OSSwapInt32 = _libkern.OSSwapInt32
    _OSSwapInt32.restype = ctypes.c_uint32
    
    _OSSwapInt64 = _libkern.OSSwapInt64
    _OSSwapInt64.restype = ctypes.c_uint64
    
    
    def apg_bswap16(x):
        x = ctypes.c_uint16(x)
        return _OSSwapInt16(x)
    
    
    def apg_bswap32(x):
        x = ctypes.c_uint32(x)
        return _OSSwapInt32(x)
    
    
    def apg_bswap64(x):
        x = ctypes.c_uint64(x)
        return _OSSwapInt64(x)
        
# __OpenBSD__
elif platform.system() == 'OpenBSD':
    _libc = _get_libc()

    _memcpy = _libc.memcpy
    
    _swap16 = _libc.swap16
    _swap16.restype = ctypes.c_uint16
    
    _swap32 = _libc.swap32
    _swap32.restype = ctypes.c_uint32
    
    _swap64 = _libc.swap64
    _swap64.restype = ctypes.c_uint64

    def apg_bswap16(x):
        x = ctypes.c_uint16(x)
        return _swap16(x)
    
    
    def apg_bswap32(x):
        x = ctypes.c_uint32(x)
        return _swap32(x)
    
    
    def apg_bswap64(x):
        x = ctypes.c_uint64(x)
        return _swap64(x)
    

# __NetBSD__, __FreeBSD__
elif platform.system() in ('NetBSD', 'FreeBSD'):
    _libc = _get_libc()

    _memcpy = _libc.memcpy
    
    _bswap16 = _libc.bswap16
    _bswap16.restype = ctypes.c_uint16
    
    _bswap32 = _libc.bswap32
    _bswap32.restype = ctypes.c_uint32
    
    _bswap64 = _libc.bswap64
    _bswap64.restype = ctypes.c_uint64

    def apg_bswap16(x):
        x = ctypes.c_uint16(x)
        return _bswap16(x)
    
    
    def apg_bswap32(x):
        x = ctypes.c_uint32(x)
        return _bswap32(x)
    
    
    def apg_bswap64(x):
        x = ctypes.c_uint64(x)
        return _bswap64(x)

# __linux__, __CYGWIN__
elif platform.system() in ('Linux', 'Cygwin'):
    _libc = _get_libc()

    _memcpy = _libc.memcpy
    
    _bswap_16 = _libc.bswap_16
    _bswap_16.restype = ctypes.c_uint16
    
    _bswap_32 = _libc.bswap_32
    _bswap_32.restype = ctypes.c_uint32
    
    _bswap_64 = _libc.bswap_64
    _bswap_64.restype = ctypes.c_uint64


    def apg_bswap16(x):
        x = ctypes.c_uint16(x)
        return _bswap_16(x)
    
    
    def apg_bswap32(x):
        x = ctypes.c_uint32(x)
        return _bswap_32(x)
    
    
    def apg_bswap64(x):
        x = ctypes.c_uint64(x)
        return _bswap_64(x)

else:
    def apg_bswap16(x):
        x = ctypes.c_uint16(x).value
        return ctypes.c_uint16(
            ((x << 8) & 0xff00) | 
            ((x >> 8) & 0x00ff)
        ).value
    
    
    def apg_bswap32(x):
        x = ctypes.c_uint32(x).value

        return ctypes.c_uint32(
            ((x << 24) & 0xff000000) | 
            ((x << 8) & 0x00ff0000) |
            ((x >> 8) & 0x0000ff00) | 
            ((x >> 24) & 0x000000ff)
        ).value
    
    def apg_bswap64(x):
        x = ctypes.c_uint64(x).value
        return ctypes.c_uint64(
            ((x << 56) & 0xff00000000000000) |
            ((x << 40) & 0x00ff000000000000) |
            ((x << 24) & 0x0000ff0000000000) |
            ((x << 8) & 0x000000ff00000000) |
            ((x >> 8) & 0x00000000ff000000) |
            ((x >> 24) & 0x0000000000ff0000) |
            ((x >> 40) & 0x000000000000ff00) |
            ((x >> 56) & 0x00000000000000ff)
        ).value
    
    _memcpy = ctypes.memmove
    

__LITTLE_ENDIAN = 1234
__BIG_ENDIAN = 4321


if sys.byteorder == "little":
    __BYTE_ORDER = __LITTLE_ENDIAN
else:
    __BYTE_ORDER = __BIG_ENDIAN


if __BYTE_ORDER == __BIG_ENDIAN:
    
    def apg_hton16(x):
        return x
        
        
    def apg_hton32(x):
        return x
        
        
    def apg_hton64(x):
        return x
    
    def apg_ntoh16(x):
        return x
        
        
    def apg_ntoh32(x):
        return x
        
        
    def apg_ntoh64(x):
        return x


elif __BYTE_ORDER == __LITTLE_ENDIAN:

    def apg_hton16(x):
        return apg_bswap16(x)
        
        
    def apg_hton32(x):
        return apg_bswap32(x)
        
        
    def apg_hton64(x):
        return apg_bswap64(x)


    def apg_ntoh16(x):
        return apg_bswap16(x)
        
        
    def apg_ntoh32(x):
        return apg_bswap32(x)
        
        
    def apg_ntoh64(x):
        return apg_bswap64(x)

else:

    raise RuntimeError('Unsupported byte order.')


def pack_int16(buf, x):
    nx = ctypes.c_uint16(apg_hton16(ctypes.c_uint16(x).value))
    
    # NOTE: the memcpy below is _important_ to support systems
    # which disallow unaligned access.  On systems, which do
    # allow unaligned access it will be optimized away by the
    # compiler
    _memcpy(buf, ctypes.byref(nx), ctypes.sizeof(ctypes.c_uint16))


def pack_int32(buf, x):
    nx = ctypes.c_uint32(apg_hton32(ctypes.c_uint32(x).value))
    _memcpy(buf, ctypes.byref(nx), ctypes.sizeof(ctypes.c_uint32))


def pack_int64(buf, x):
    nx = ctypes.c_uint64(apg_hton64(ctypes.c_uint64(x).value))
    _memcpy(buf, ctypes.byref(nx), ctypes.sizeof(ctypes.c_uint64))


def unpack_uint16(buf):
    nx = ctypes.c_uint16()
    _memcpy(
        ctypes.cast(ctypes.POINTER(ctypes.c_char), ctypes.byref(nx)), 
        buf, 
        ctypes.sizeof(ctypes.c_uint16)
    )
    return apg_ntoh16(nx)


def unpack_int16(buf):
    return ctypes.c_int16(unpack_uint16(buf)).value


def unpack_uint32(buf):
    nx = ctypes.c_uint32()
    _memcpy(
        ctypes.cast(ctypes.POINTER(ctypes.c_char), ctypes.byref(nx)),
        buf, 
        ctypes.sizeof(ctypes.c_uint32)
    )
    return apg_ntoh32(nx)


def unpack_int32(buf):
    return ctypes.c_int32(unpack_uint32(buf))


def unpack_uint64(buf):
    nx = ctypes.c_uint64()
    _memcpy(
        ctypes.cast(ctypes.POINTER(ctypes.c_char), ctypes.byref(nx)), 
        buf, 
        ctypes.sizeof(ctypes.c_uint64)
    )
    return apg_ntoh64(nx.value)


def unpack_int64(buf):
    return ctypes.c_int64(unpack_uint64(buf))


class _apg_floatconv(ctypes.Union):
    _fields_ = [
        ('i', ctypes.c_uint32),
        ('f', ctypes.c_float)
    ]


class _apg_doubleconv(ctypes.Union):
    _fields_ = [
        ('i', ctypes.c_uint64),
        ('f', ctypes.c_double)
    ]


def pack_float(buf, f):
    v = _apg_floatconv()
    v.f = f
    pack_int32(buf, ctypes.c_int32(v.i))


def pack_double(buf, f):
    v = _apg_doubleconv()
    v.f = f
    pack_int64(buf, ctypes.c_int64(v.i).value)


def unpack_float(buf):
    v = _apg_floatconv()
    v.i = ctypes.c_uint32(unpack_int32(buf)).value
    return v.f


def unpack_double(buf):
    # unpack_double(const int64_t a)
    v = _apg_doubleconv()
    v.i = ctypes.c_uint64(unpack_int64(buf)).value
    # v.i = (uint64_t)unpack_int64(a);
    return v.f

```

**Comment by kdschlosser** [comment]
I know this is for your personal use but if someone by chance uses it and doesn't have Cython installed then something like the above would still work even tho it has not been compiled using Cython

**Comment by wolph** [comment]
This repo isn't only for personal use actually, but I do think you are misunderstanding the point of the repo :)

It is an optional speed-up to make things as fast as possible. If the speedup is not available it will not use this speedup module and use regular Python code instead.

While the code you have posted here is similar in workings, I doubt that the code will have the same performance. Especially when it comes to the `nogil` part, that is not something easily worked around in pure Python :)

**Comment by kdschlosser** [comment]
if you compile that code using Cython you will get all of the speedups that can be gotten from using a C extension. It didn't have to be written in C in order to get that performance boost.
You can compile just about any .py  file using Cython and get the performance increase. That is one of the cool things about Cython is it's ability to convert python code to C code. The neat thing about that is you do not have to maintain a pure python version of the code and also a version written in C. from a maintenance standpoint it makes things a whole lot easier. In your specific use  case you have to maintain 3 different code bases, Python, Cython and C. and the 3 of them have to interact with each other and that really complicates the shit out of things. Ya know? LOL.

**Comment by kdschlosser** [comment]
also your use of nogil in a python function isn't going to actually do anything of value. Because the call to the function is being made when the gil is already locked and nogil whether or not the gil is locked is going to allow the code to run. You get NO speed boost from not having the gil locked.

https://stackoverflow.com/questions/65834960/do-i-need-to-use-nogil-in-cython

The gil is only there to make sure that a single python thread runs at a time. so because the call to the function is being made from a python thread the gil does not get unlocked in the loop. the other thing is you should be using `prange` since you are wanting to unlock the gil.

https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html

**Comment by wolph** [comment]
I am aware that running Cython on regular Python code makes it faster, but doing it with the proper C types so you don't have to convert to Python types is even faster. Just look at the benchmark in the Cython tutorial: https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html

```
python -m timeit -s 'from primes_python import primes' 'primes(1000)'
10 loops, best of 3: 23 msec per loop

python -m timeit -s 'from primes_python_compiled import primes' 'primes(1000)'
100 loops, best of 3: 11.9 msec per loop

python -m timeit -s 'from primes import primes' 'primes(1000)'
1000 loops, best of 3: 1.65 msec per loop
```

The compiled Python version is quite a bit faster (11.9ms) than the regular Python version (23ms) but still much slower than the proper Cython version (1.65ms).

The loops in this bit of code cannot be run using `prange` because it doesn't know the size in advance and needs to increment the pointer based on the size it has read in the previous iteration.

But there's another reason for wanting to unlock the gil, it allows Python to run code in other threads while this operation is running :)

**Comment by kdschlosser** [comment]
I am trying to understand the layout of the data. From my interpretation of the code it is something like this

bytes    

0   1   2   3 = rows

4   5   6   7 = data offset
8   9   10   11 = oid

each dimension is 8 bytes long and a dimension is broken into 2 parts, the dimension and the lbound each of which are 4 bytes


12   13   14   15  = dimension
16   17   18   19 = lbound

20   21   22   23  = dimension
24    25    26   27 = lbound

I am thinking that dimension is the number of elements in a row.

Once you get past the header and dimension header data the rest of the memoryview is the elements
the element data is broken into blocksad the length of the bock depends on the datatype

so if the data type is 16 bit integer each data block is 6 bytes long and for a 32 bit integer the data block is 8 bytes long. The first 4 bytes of the block is the size and the rest of the bytes is the element data.

What confuses me if the setting of the numpy array for a specific data type and then checking the first 4 bytes of the element data for the size to determine the proper unpack function to call. This seems kind of redundant and wasteful. You already know the data type so why check it again for every single element???

If the data is actually laid out like what I have described above there is no need to monkey about with 1/2 of the stuff you have. Move the code that iterates over the dimension header into Cython code and build an array of those dimension numbers. add the dimension numbers together as you iterate over the dimension header to get the total number of elements. after you have all of the dimensions create the numpy array using `numpy.empty(dimensions, dtype=numpy.dtype('>{data type'))`  Because you know the data type you know the number of bytes to the element data and that makes it easy to iterate over the element data. simply disregard the first 4 bytes and move the rest of the element bytes into the array.

The data that is being read is big-edian and using one of the following types handles all of the work for you without the need for and of the stuff in hton
">f" - 32 bit float
">d" - double (64 bit float)
">u2" - 16 bit unsigned integer
">u4" - 32 bit unsigned integer
">u8" - 64 bit unsigned integer

the ">" means the data is formatted using big-edian and numpy internally will handle sorting out the byte order to return the correct value.

**Comment by wolph** [comment]
The code is currently slightly more flexible than is needed for numbers. In the case of text the size is variable due to multi-byte characters and such. That's why it needs to be read iteratively :)

The plan is to eventually support more types so I didn't want to limit the current code to numbers alone.

With regards to the big-endian stuff, that's the first thing I tried of course, but that doesn't seem to work with numpy.

**Comment by kdschlosser** [comment]
I have not tried it myself and it should work. If it doesn't then it's broken and I wonder if it has been reported that it's broken. The numbers being passed is network data so it's big-edian and the numbers should be presented properly on a system that is little-edian. That is very strange tho I will say that. I didn't think you missed it but I found it strange that you were not suing it as it would be by far the easiest way to go about doing it.

I am going to run some tests against numpy to see what's up with it.

**Comment by kdschlosser** [comment]
OK it does work. In a half ass round about way.


```python
import numpy as np


bts = bytearray([255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255])
bts = bytes(bts)

array1 = np.array(np.frombuffer(bts, dtype=np.dtype('>u8')))
array2 = np.array(np.frombuffer(bts, dtype=np.dtype('<u8')))

print(array1)
print(array2)


for item in array1:
    print(item)

print()

for item in array2:
    print(item)

print(array1[0] == array2[1], array1[1] == array2[0])
```

and the output is

```
[18374686479671623680                  255]
[                 255 18374686479671623680]
18374686479671623680
255

255
18374686479671623680
True True
```

which is what it should be. they are reversed from each other.
